In [2]:
import pandas as pd

vendors = pd.read_excel("vendors.xlsx")
customers = pd.read_excel("customers.xlsx")
purchases = pd.read_excel("purchases.xlsx")
sales = pd.read_excel("sales.xlsx")
highest_selling = pd.read_excel("highest_selling.xlsx")

In [4]:
vendors.head()

,Vendor Name,Total Bills,Bill Amount,Debit Note Amount,Paid Amount,Unpaid Amount,Average Bill Value
0,UMIYA TOOL ROOM,2,27642,0,27642,0,13821.00
1,Radhe Sales,1,18290,0,18290,0,18290.00
2,ATUL STEEL TRADERS,2,12440,0,12440,0,6220.00
3,PERFECT STEEL CORPORATION,3,11669,0,11669,0,3889.67
4,DURGA STEEL CORPORATION,2,2257,0,2257,0,1128.50

In [5]:
vendors.isnull().sum()

Vendor Name           0
Total Bills           0
Bill Amount           0
Debit Note Amount     0
Paid Amount           0
Unpaid Amount         0
Average Bill Value    0
dtype: int64

In [6]:
vendors.dropna(inplace=True)

In [7]:
vendors.drop_duplicates(inplace=True)

In [8]:
vendors['Total Bills'] = pd.to_numeric(vendors['Total Bills'])

In [9]:
vendors.sort_values(
    by='Total Bills',
    ascending=False
)

,Vendor Name,Total Bills,Bill Amount,Debit Note Amount,Paid Amount,Unpaid Amount,Average Bill Value
3,PERFECT STEEL CORPORATION,3,11669,0,11669,0,3889.67
0,UMIYA TOOL ROOM,2,27642,0,27642,0,13821.00
2,ATUL STEEL TRADERS,2,12440,0,12440,0,6220.00
4,DURGA STEEL CORPORATION,2,2257,0,2257,0,1128.50
1,Radhe Sales,1,18290,0,18290,0,18290.00
5,PUSHTI TRADERS,1,2145,0,2145,0,2145.00
6,VANSH GLOBAL,1,1652,0,1652,0,1652.00
7,Total,0,0,0,76095,0,6341.25

In [10]:
customers.sort_values(
    by='Total',
    ascending=False
)

,Name,Invoice Count,Retail Invoice Count,Credit Note Count,Amount,Tax,Round Off,Total
2,BANSIDHAR AGENCIES,3,0,0,135663,24419.34,-0.18,160082.34
3,FLUOROPLAST ENGINEERS PRIVATE LIMITED,2,0,0,128570,23142.60,0.40,151712.60
6,ANUPAM INDUSTRIES LTD.( UNIT I),1,0,0,107500,19350.00,0.00,126850.00
5,GEMBA METAL FORMING PRIVATE LIMITED,3,0,0,15000,2700.00,0.00,17700.00
4,SHIV FABRICATORS,1,0,0,9386,1689.48,-0.48,11075.48
0,Formoed Wide Span Structure Pvt Ltd,1,0,0,5810,1045.80,-0.20,6855.80
1,Mech Tech Engineering Co.,1,0,0,3595,647.10,-0.10,4242.10

In [11]:
sales.sort_values(
    by='Quantity Sold',
    ascending=False
)

,Item Name,Quantity Sold,Average Price,Amount,Tax,Amount With Tax
0,55x2000x2mm PP strips for holes Punching,12857,10.0,128570,23142.60,151712.60
3,Aluminium profile section 27mm hole Punching :...,3444,11.0,37884,6819.12,44703.12
14,Aluminium profile section 27mm holes punching ...,2281,7.0,15967,2874.06,18841.06
5,Rubber shoes drilling and fitting for aluminiu...,1717,11.0,18887,3399.66,22286.66
17,50 x 50 x 3mm square cutting and 10mm hole pun...,1438,2.5,3595,647.10,4242.10
15,Rubber shoes drilling and fitting in Aluminium...,1226,11.0,13486,2427.48,15913.48
1,Aluminium profile section 27mm hole Punching :...,992,19.0,18848,3392.64,22240.64
12,15x15x1.5mm angle punching job work hole size 5mm,830,7.0,5810,1045.80,6855.80
4,Rubber shoes drilling and fitting for aluminiu...,724,11.0,7964,1433.52,9397.52
7,SS circle sheet turning job work,722,13.0,9386,1689.48,11075.48
16,Aluminium ladder assemble work - 8 feet length,525,15.0,7875,1417.50,9292.50
2,Transportation per labour,81,167.0,13527,2434.86,15961.86
6,Aluminium ladder assemble work length -20feet,35,35.0,1225,220.50,1445.50
8,18 X 40 MM CAPSULE PUNCHING DIE,5,11000.0,55000,9900.00,64900.00
9,12 X 32 MM CAPSULE PUNCHING DIE,5,10500.0,52500,9450.00,61950.00
11,Punching die repair,2,2500.0,5000,900.00,5900.00
10,Piercing tool -8213/14,1,9000.0,9000,1620.00,10620.00
13,EN 31 KEY,1,1000.0,1000,180.00,1180.00

In [13]:
!pip install mysql-connector-python sqlalchemy

Requirement already satisfied: mysql-connector-python in c:\users\vrunda\anaconda3\lib\site-packages (9.7.0)
Requirement already satisfied: sqlalchemy in c:\users\vrunda\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\vrunda\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\vrunda\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [16]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+mysqlconnector://root:Vrunda%40123@localhost/manufacturing"
)

In [17]:
vendors.to_sql(
    'vendors',
    con=engine,
    if_exists='replace',
    index=False
)

customers.to_sql(
    'customers',
    con=engine,
    if_exists='replace',
    index=False
)

sales.to_sql(
    'sales',
    con=engine,
    if_exists='replace',
    index=False
)

purchases.to_sql(
    'purchases',
    con=engine,
    if_exists='replace',
    index=False
)

14

In [18]:
sales.columns = [
    'item',
    'quantity_sold',
    'average_price',
    'amount',
    'tax',
    'amount_with_tax'
]

print(sales.columns)

Index(['item', 'quantity_sold', 'average_price', 'amount', 'tax',
       'amount_with_tax'],
      dtype='object')

In [19]:
purchases.columns = [
    'item',
    'quantity_purchased',
    'average_price',
    'amount',
    'amount_with_tax'
]

print(purchases.columns)

Index(['item', 'quantity_purchased', 'average_price', 'amount',
       'amount_with_tax'],
      dtype='object')

In [20]:
customers.columns = [
    'customer_name',
    'invoice_count',
    'retail_invoice_count',
    'credit_note_count',
    'amount',
    'tax',
    'round_off',
    'total'
]

print(customers.columns)

Index(['customer_name', 'invoice_count', 'retail_invoice_count',
       'credit_note_count', 'amount', 'tax', 'round_off', 'total'],
      dtype='object')

In [21]:
vendors.columns = [
    'vendor_name',
    'total_bill',
    'bill_amount',
    'debit_note_amount',
    'paid_amount',
    'unpaid_amount',
    'average_bill_value'
]

print(vendors.columns)

Index(['vendor_name', 'total_bill', 'bill_amount', 'debit_note_amount',
       'paid_amount', 'unpaid_amount', 'average_bill_value'],
      dtype='object')

In [23]:
highest_selling.columns = [
    'item',
    'sku',
    'unit',
    'quantity',
    'amount',
    'tax',
    'amount_with_tax'
]

print(highest_selling.columns)

Index(['item', 'sku', 'unit', 'quantity', 'amount', 'tax', 'amount_with_tax'], dtype='object')

In [24]:
sales.to_sql(
    'sales',
    con=engine,
    if_exists='replace',
    index=False
)

purchases.to_sql(
    'purchases',
    con=engine,
    if_exists='replace',
    index=False
)

customers.to_sql(
    'customers',
    con=engine,
    if_exists='replace',
    index=False
)

vendors.to_sql(
    'vendors',
    con=engine,
    if_exists='replace',
    index=False
)

highest_selling.to_sql(
    'highest_selling',
    con=engine,
    if_exists='replace',
    index=False
)

16